blog/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
                        url(r'^$',"blog.views.home", name='inicio'),
                        url(r'^boton_magico$',"blog.views.boton_magico",name='boton_magico'),
                        url(r'^calculadora$',"blog.views.calculadora",name='calculadora'),
                        url(r'^contactos$',"blog.views.contactos",name='contactos'),
                        url(r'^conversor$',"blog.views.conversor",name='conversor'),
                        url(r'^cronometro$',"blog.views.cronometro",name='cronometro'),
                        url(r'^cv$',"blog.views.cv",name='cv'),
                        url(r'^image$',"blog.views.image",name='image'),
                        url(r'^ver_post/(?P<id_post>[0-9]+)/$',"blog.views.verpost",name='verpost'),     
                        url(r'^mensaje/$',"blog.views.mensaje",name='mensaje'),  
)

chucho/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from chucho import settings
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^', include('blog.urls', namespace = "blog")),
    url(r'^admin/', include(admin.site.urls)),


]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Entrada(models.Model):
    class Meta:
        verbose_name = "Entrada"
        verbose_name_plural = "Todas las Entradas"
        ordering = ['-fecha']
    titulo = models.CharField(u'Título', max_length = 100)
    fecha = models.DateTimeField(u'Fecha del Post',auto_now_add=True)
    resumen= models.CharField(u'Resumen',max_length=512)
    contenido = models.TextField(u'Contenido')
    def __str__(self):
        return self.titulo

class Mensajes(models.Model):
    class Meta:
        verbose_name = "Comentario"
        verbose_name_plural = "Comentarios"
    nombre = models.CharField('Nombre:', max_length = 100)
    contenido = models.TextField('Mensaje:')
    able = models.BooleanField('Habilitado:', default = True)
    pub_en = models.ForeignKey(Entrada)
    def __str__(self):
        return self.nombre

blog/views.py
from django.template import RequestContext
from django.shortcuts import render_to_response,render,redirect
from blog.models import Entrada, Mensajes

# Create your views here.
def home(request):
    context= RequestContext(request)
    entradas = Entrada.objects.all()
    return render_to_response('Inicio.html',{"entradas":entradas},context)

def mensaje(request):
    context = RequestContext(request)
    mensajes = None
    if request.method == "POST":
        de_post = Entrada.objects.get(id=request.POST['id'])
        nombre = request.POST["nombre"]
        mensaje = request.POST["mensaje"]
        men = Mensajes()
        men.nombre = nombre
        men.mensaje = mensaje
        men.pub_en = de_post
        men.save()
        mensajes = Mensajes.objects.filter(pb_en=de_post, able=True)

        return render_to_response('mensajes.html',{'mensajes':mensajes},context)

def boton_magico(request):
    context= RequestContext(request)
    return render_to_response('boton_magico.html',{},context)
def calculadora(request):
    context= RequestContext(request)
    return render_to_response('Calculadora.html',{},context)
def contactos(request):
    context= RequestContext(request)
    if request.method=="post":
        nombre = request.POST["Nombre"]
        email = request.POST["Email"]
        contenido = request.POST["Mensaje"]
        send_mail(str(nombre),str(contenido),email,["acairiaelemail@gmail.com"],fail_silently=False)
    return render_to_response('Contactos.html',{},context)
def conversor(request):
    context= RequestContext(request)
    return render_to_response('conversor.html',{},context)
def cronometro(request):
    context= RequestContext(request)
    return render_to_response('cronometro.html',{},context)
def cv(request):
    context= RequestContext(request)
    return render_to_response('CV.html',{},context)
def image(request):
    context= RequestContext(request)
    return render_to_response('Image.html',{},context)

def verpost(request,id_post):
    context= RequestContext(request)
    mi_post = Entrada.objects.get(id = id_post)
    if request.method=="POST":
        nombre=request.POST["nombre"]
        contenido=request.GET["mensaje"]
        mensaje=Mensajes()
        mensaje.nombre=nombre
        mensaje.mensaje=contenido
        mensaje.pub_en=mi_post
        mensaje.save()
    mensaje = Mensajes.objects.filter(pub_en = id_post)
    return render_to_response('post.html',{"post":mi_post,"mensajes":mensaje},context)
    
	

blog/templates/CV.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block titulo %}
                                                                                                                                                                                                                                                                                          
<title>CV</title>
{% endblock %}
{% block title %}
Curriculum Vitae
{% endblock %}
{% block content %}
        <div class="container center-align">
            <IMG SRC="{% static 'img/giphy.gif'%}"><br>
                <h2>Informacion Personal</h2><br>
                <p>Nombre:Matias<br>
                Apellido:Ferreyra<br>
                Edad:16<br>
                Correo Elecetronico: suwindows7noesoriginal@gmail.com<br>
                Direccion:Calle Chucho 1111, B° Chucho, Tucuman, Argentina.
                Nacionalidad:Argentina<br>
                Telefono:123456789<br>
                Estado Marital:Soltero<br></p>
        </div>
{% endblock %}

blog/templates/Calculadora.html
{% extends 'base.html' %}
{% block titulo %}
<title>Calculadora</title>
{% endblock %}
{% block title %}
Calculadora
{% endblock %}
{% block content %}
        <div class="container">
            <div style="text-align:center">

                <div class="row center" style="width:200px;"><input disabled value="0" id="display" style="text-align:center; margin-left:180%;" type="text" class="validate white-text"> <br></div>
                <a type="button" value="1" onclick="calcular(this)"class="waves-effect waves-light btn">1</a>
                <a type="button" value="2" onclick="calcular(this)"class="waves-effect waves-light btn">2</a>
                <a type="button" value="3" onclick="calcular(this)"class="waves-effect waves-light btn">3</a>
                <a type="button" value="+" onclick="calcular(this)"class="waves-effect waves-light btn">+</a><br>
                <a type="button" value="4" onclick="calcular(this)"class="waves-effect waves-light btn">4</a>
                <a type="button" value="5" onclick="calcular(this)"class="waves-effect waves-light btn">5</a>
                <a type="button" value="6" onclick="calcular(this)"class="waves-effect waves-light btn">6</a>
                <a type="button" value="-" onclick="calcular(this)"class="waves-effect waves-light btn">-</a><br>
                <a type="button" value="7" onclick="calcular(this)"class="waves-effect waves-light btn">7</a>
                <a type="button" value="8" onclick="calcular(this)"class="waves-effect waves-light btn">8</a>
                <a type="button" value="9" onclick="calcular(this)"class="waves-effect waves-light btn">9</a>
                <a type="button" value="*" onclick="calcular(this)"class="waves-effect waves-light btn">*</a><br>
                <a type="button" value="0" onclick="calcular(this)"class="waves-effect waves-light btn">0</a>
                <a type="button" value="/" onclick="calcular(this)"class="waves-effect waves-light btn">/</a>
                <a type="button" value="=" onclick="calcular(this)"class="waves-effect waves-light btn">=</a>
                <a type="button" value="CE" onclick="calcular(this)"class="waves-effect waves-light btn">CE</a><br>

            </div>
        </div>
{% endblock %}
{% block scripts %}
<script>

    function calcular(boton){

        var btn = boton.getAttribute("value");
        console.log(btn);
        var display = document.getElementById("display");

        if(display.value=="0"){
            display.value="";
        }

        if(btn=="="){
            resultado=eval(display.value); 
            display.value=resultado;
        }else{
            if(btn=="CE"){
                display.value=0;
            }else{
                display.value=display.value+btn;
            }
        }
    }

</script>
{% endblock %}

blog/templates/Contactos.html
{% extends 'base.html' %}
{% block titulo %}
<title>Contactos</title>
{% endblock %}
{% block title %}
Contactos
{% endblock %}
{% block content %}
<div class="container ">
    <form >
        <div class="input-field col s6">
            <input id="ContactosNombre" type="text" name="Nombre"></input>
            <label for="ContactosNombre">Nombre</label>
        </div>
        <div class="input-field col s6">
            <input id="ContactosEmail" type="text" name="Email"></input>
            <label for="ContactosEmail">Email</label>
        </div>
        <div class="input-field col s6">
            <textarea id="ContactosContenido" class="materialize-textarea" type="text" name="Mensaje"></textarea><br>
            <label for="ContactosContenido">Mensaje</label>
        </div>
    <div class="center-align">
        <a type="submit" value="Enviar" class="waves-effect waves-light btn">Enviar</a>
    </div>
    </form>
</div>
{% endblock %}

blog/templates/Image.html
<html>	
    <head>
        <!--Import materialize.css-->
        <link type="text/css" rel="stylesheet" href="css/materialize.min.css"  media="screen,projection"/>
{% extends 'base.html' %}
{% block titulo %}
{% load staticfiles%}
<title>Image</title>
{% endblock %}
{% block title %}
Imagenes
{% endblock %}
{% block content %}


        <div class="content" align="center">
            <h3>Imagenes Aleatorias</h3>
            <progress id="barra" max="100" value="0"></progress><br><br>
            <img id="img" height = "400px" width="400px" src="{% static 'img/1.jpg'%}"/>

        </div>
{% endblock %}
{% block scripts %}
<script>
    var images = ["1.jpg","2.jpg","3.jpg","4.jpg"];
    var tiempo = setInterval(function(){load();},1000);

    $(document).ready(function(){
        load();
    });

    var barra = document.getElementById("barra");
    var img = document.getElementById("img");
    a = 0;
    i = 1;
    var time = setInterval(load, 50);

    function load(){
        a +=5 ;
        barra.value = a;
        if (barra.value == 100){
            a=0;
            barra.value = a;
            img.setAttribute("src","{% static  'img/' %}"+images[i]);
            i++;
            if(i==4){i=0}
        }
    }
</script>
{% endblock %}

blog/templates/Inicio.html
{% extends 'base.html' %}
{% block titulo %}
<title>Inicio</title>
{% endblock %}
{% block title %}
Inicio
{% endblock %}
{% block content %}
<div class="container center-align">
{% for entrada in entradas %}
<div class=" card-panel teal lighten-2">           
    <h4><a href="{% url 'blog:verpost' entrada.id %}">{{entrada.titulo}}</a></h3><br>
    <p>{{entrada.resumen}}</p><br>   
</div>
{% endfor %}
</div>
{% endblock %}

blog/templates/base.html
{% load staticfiles %}
<html>	
    <head>
        <!--Import materialize.css-->
        <link type="text/css" rel="stylesheet" href="{% static 'css/materialize.min.css' %}"  media="screen,projection"/>
        <link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}" />

        <!--Let browser know website is optimized for mobile-->
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
        <!-----------------------------------------------| IMPORTAR |-------------------------------------------------------------->
        <meta http-equiv="Content-type" content="text/html; charset=utf-8">
        <link rel="stylesheet" href="{% static 	'css/materialize.css' %}">
        <link rel="stylesheet" href="{% static 	'css/style.css' %}">

{% block titulo %}

        {% endblock %}
    </head>
    <body class="cyan darken-3">

        <!-----------------------------------------------| IMPORTAR JS |-------------------------------------------------------------->
        <script type="text/javascript" src="{% static 'js/jquery-1.11.3.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/materialize.min.js' %}"></script>
        <!-----------------------------------------------| IMPORTAR JS |-------------------------------------------------------------->
        <div class="cabeza">
            <h1 style="color:white">El blog de Chucho</h1>
        </div>
        <div style="margin_right:300px;">
            <ul id='dropdown1' class='dropdown-content'>
                <li><a href="{% url 'blog:calculadora' %}">Calcu</a></li>
                <li class="divider"></li>
                <li><a href="{% url 'blog:conversor' %}">Conver</a></li>
                <li class="divider"></li>
                <li><a href="{% url 'blog:cronometro' %}">Crono</a></li>
                <li class="divider"></li>
                <li><a href="{% url 'blog:boton_magico' %}">Chiste</a></li>
                <li class="divider"></li>
                <li><a href="{% url 'blog:image' %}">Imagenes</a></li>
            </ul>
        </div>
        <nav>
            <div class="nav-wrapper teal lighten-2">
                <a href="#" class="brand-logo left " >{% block title %}{% endblock %}</a>
                <ul id="nav-mobile" class="right hide-on-med-and-down">
                    <li><a href="{% url 'blog:inicio' %}" >Inicio</a></li>
                    <li><a href="{% url 'blog:contactos' %}" >Contactos</a></li>
                    <li><a href="{% url 'blog:cv' %}" >Curriculum</a></li>
                    <li><a class="dropdown-button" href="#!" data-activates="dropdown1">Ejercicios</a>
                </ul>
            </div>
        </nav>
        {% block content %}
        {% endblock %}
        <footer class="page-footer"/>
            <div class="teal lighten-1">
                <div class="container">
                    <div class="row">
                        <div class="col l6 s12">
                            <h5 class="white-text">Hola</h5>
                            <p class="grey-text text-lighten-4">En este lugar tendria que haber algo interesante, pero no se que poner</p>
                        </div>
                        <div class="col l4 offset-l2 s12">
                            <h5 class="white-text">Seguime en</h5>
                            <ul>
                                <li><a class="grey-text text-lighten-3" href="https://www.facebook.com/?_rdr">Facebook</a></li>
                                <li><a class="grey-text text-lighten-3" href="https://twitter.com/?lang=es">Twitter</a></li>
                                <li><a class="grey-text text-lighten-3" href="https://plus.google.com/?hl=es">Google+</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="footer-copyright">
                    <div class="container">
                        "Live slow, Die whenever."
                    </div>
                </div>
            </div>
        </footer>
    </body>   
{% block scripts %}
            
    {% endblock %}

</html>

blog/templates/boton_magico.html
{% load staticfiles %}
<html>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8">
    <link rel="stylesheet" href="css/style.css">
    <head>
        <h1>La pagina se esta redireccionando</h1>
    </head>
    <body>
        <div class="boton_magico">
            <input type="button" id="magico" value="Continuar" onmouseover="troll()" onclick="win()" ></input>
        </div>
    </body>

</html>
<script>
    function troll(){
        document.getElementById("magico").style.marginTop = Math.floor((Math.random()*400) + 1);
        document.getElementById("magico").style.marginLeft = Math.floor((Math.random()*400) + 1);
    }
    function win(){
        alert("¡Ganaste!");
        location.href="{% url 'blog:inicio' %}";
    }
</script>

blog/templates/conversor.html
{% extends 'base.html' %}
{% block titulo %}
<title>Conversor</title>
{% endblock %}
{% block title %}
Conversor
{% endblock %}
{% block content %}
        <div class="container">



            <div style="color:white">
                De<select id="tipoMoneda" class="col l5 offset-l1"> 
                <option selected>Seleccionar Tipo de Moneda</option>
                <option value="1">Pesos Argentinos </option> 
                <option value="2">Dolares </option> 
                <option value="3">Euros </option> 
                <option value="4">Pesos Uruguayos</option>
                <option value="5">Pesos Chilenos</option></select>
                <input type="text" id="valor" value=""></input>
        </div>
        <div style="color:white">
            De<select id="TipoMonedaFinal"> 
            <option selected>Seleccionar Tipo de Moneda</option>
            <option value="1">Pesos Argentinos </option> 
            <option value="2">Dolares </option> 
            <option value="3">Euros </option> 
            <option value="4">Pesos Uruguayos</option>
            <option value="5">Pesos Chilenos</option></select>
            <input type="text" id="valorFinal" value=""></input>
        </div>

    <div class="center-align">
        <a type="button" id="botonConvertir" value="Convertir" onclick="cambio()" class="btn-large waves-effect waves-light">Convertir</a> 
        <a type="button" id="botonLimpiar" value="Limpiar" onclick="limpieza()" class="waves-effect waves-light btn-large">Limpiar</a>
    </div>
    </div>
{% endblock %}
{% block scripts %}
<script>
    function limpieza(){
        document.getElementById("valorFinal").value = "";
        document.getElementById("valor").value = "";
    }
    function cambio(){
        var seleccion1 = document.getElementById("tipoMoneda");
        var valorSeleccion1 =seleccion1.options[seleccion1.selectedIndex].value;

        var seleccion2 = document.getElementById("TipoMonedaFinal"); 
        var valorSeleccion2 = seleccion2.options[seleccion2.selectedIndex].value;
        console.log(valorSeleccion1);
        console.log(valorSeleccion2);
        var valorDivisa=0.0;

        switch(parseInt(valorSeleccion1)) {
            case 1:

                switch(parseInt(valorSeleccion2)) {
                    case 1:
                        valorDivisa=1;
                        break;
                    case 2:
                        valorDivisa=0.11231;
                        break;
                    case 3:
                        valorDivisa=0.10396;
                        break;    
                    case 4:
                        valorDivisa=68.540;
                        break;
                    case 5:
                        valorDivisa=2.9911;
                        break;
                    case 0:
                        alert("Debe Seleccionar una Divisa");
                        break;
                }
                break;
            case 2:
                switch(parseInt(valorSeleccion2)) {
                    case 1:
                        console.log("enter");
                        valorDivisa=8.8968;
                        break;
                    case 2:
                        valorDivisa=1.0;
                        break;
                    case 3:
                        valorDivisa=0.92687;
                        break;    
                    case 4:
                        valorDivisa=609.79;
                        break;
                    case 5:
                        valorDivisa=26.611;
                        break;
                    case 0:
                        alert("Debe Seleccionar una Divisa");
                        break;
                }
                break;
            case 3:
                switch(parseInt(valorSeleccion2)) {
                    case 1:
                        valorDivisa=9.5988;
                        break;
                    case 2:
                        valorDivisa=1,0755;
                        break;
                    case 3:
                        valorDivisa=1;
                        break;    
                    case 4:
                        valorDivisa=657.90;
                        break;
                    case 5:
                        valorDivisa=28.711;
                        break;
                    case 0:
                        alert("Debe Seleccionar una Divisa");
                        break;
                }
                break;    
            case 4:
                switch(parseInt(valorSeleccion2)) {
                    case 1:
                        valorDivisa=0.014590;
                        break;
                    case 2:
                        valorDivisa=0.0016400;
                        break;
                    case 3:
                        valorDivisa=0.0015200;
                        break;    
                    case 4:
                        valorDivisa=1;
                        break;
                    case 5:
                        valorDivisa=0.043640;
                        break;
                    case 0:
                        alert("Debe Seleccionar una Divisa");
                        break;
                }
                break;
            case 5:
                switch(parseInt(valorSeleccion2)) {
                    case 1:
                        valorDivisa=0.33433;
                        break;
                    case 2:
                        valorDivisa=0.037580; 
                        break;
                    case 3:
                        valorDivisa=0.034830;
                        break;    
                    case 4:
                        valorDivisa=22.915;
                        break;
                    case 5:
                        valorDivisa=1;
                        break;
                    case 0:
                        alert("Debe Seleccionar una Divisa");
                        break;
                }
                break;
            case 0:
                alert("Debe Seleccionar una Divisa");
                break;
        }
        var moneda = document.getElementById("valor");
        var resultado = eval(parseFloat(moneda.value)*parseFloat(valorDivisa));
        var MostrarResultado = document.getElementById("valorFinal");
        MostrarResultado.value=resultado;
        console.log(moneda.value+" * "+ valorDivisa+" = "+resultado);
    }
    $(document).ready(function(){
        $("select").material_select()
    });
</script>
{% endblock %}

blog/templates/cronometro.html
{% extends 'base.html' %}
{% block titulo %}
<title>Cronometro</title>
{% endblock %}
{% block title %}
Cronometro
{% endblock %}
{% block content %}
        <div class="container">
            <div class="center-align" >
                <div class="nav-wrapper teal lighten-2">
                    <h2>Cronometro</h2>
                    <h4><span   id="horas">00</span>:<span id="minutos">00</span>:<span id="segundos">00</span>:<span id="decimas">00</span></h4>
                    <br>

                    <a id="start" value="Start" onclick="startCrono()" class="waves-effect waves-light btn" disable="fa"><i class="mdi-av-play-circle-outline"></i></a>
                    <a id="stop" value="Stop" onclick="stopCrono()" class="waves-effect waves-light btn" disabled="true"><i class="mdi-av-pause-circle-outline"></i></a>
                    <a id="restart" value="Reset" onclick="restart()" class="waves-effect waves-light btn"><i class="mdi-action-history
                        "></i></a>
                </div>        
            </div>
        </div>
{% endblock %}
{% block scripts %}
<script>
    var crono;

    function restart(){
        document.getElementById("horas").innerHTML="00";
        document.getElementById("minutos").innerHTML="00";
        document.getElementById("segundos").innerHTML="00";
        document.getElementById("decimas").innerHTML="00";
    }

    function startCrono(){
        document.getElementById("start").disabled=true;
        document.getElementById("stop").disabled=false;
        document.getElementById("restart").disabled=true;

        var horasElem = document.getElementById("horas");
        var minutosElem = document.getElementById("minutos");
        var segundosElem = document.getElementById("segundos");
        var decimasElem = document.getElementById("decimas");

        var horas;
        var minutos;
        var segundos;
        var decimas;

        if(horasElem.innerHTML!=0 | minutosElem.innerHTML!=0 | segundosElem.innerHTML!=0| decimasElem.innerHTML!=0){
            horas = parseInt(horasElem.innerHTML);
            minutos = parseInt(minutosElem.innerHTML);
            segundos = parseInt(segundosElem.innerHTML);
            decimas = parseInt(decimasElem.innerHTML);
        }else{
            horas = 0;
            minutos = 0;
            segundos = 0;
            decimas = 0;
        }

        crono = window.setInterval(function(){
            if(decimas!=10){
                decimas++;}
            else{
                decimas=00;segundos++;
                if(segundos==60){
                    segundos=00;minutos++;
                    if(minutos==60){
                        minutos=00;horas++;
                    }
                }
            }
            if(horas<=9){horasElem.innerHTML="0"+horas;}else{horasElem.innerHTML=horas;}
            if(minutos<=9){minutosElem.innerHTML="0"+minutos;}else{minutosElem.innerHTML=minutos;}
            if(segundos<=9){segundosElem.innerHTML="0"+segundos;}else{segundosElem.innerHTML=segundos;}
            if(decimas<=9){decimasElem.innerHTML="0"+decimas;}else{decimasElem.innerHTML=decimas;}},100);
    }

    function stopCrono(){
        document.getElementById("stop").disabled=true;
        document.getElementById("start").disabled=false;
        document.getElementById("restart").disabled=false;
        clearInterval(crono);
    }

</script>
{% endblock %}

blog/templates/mensajes.html
{% for mensaje in mensajes %}
<div>
    <h3>{{mensaje.nombre}}</h3>
    <p>{{mensaje.mensaje}}</p>
</div>  
{% endfor %}

blog/templates/post.html
{% extends 'base.html' %}
{% block titulo %}
<title>Post</title>
{% endblock %}
{% block title %}
Inicio
{% endblock %}
{% block content %}
<div class="container">
    <div class="center-align" >
        <div class="card teal lighten-2">
            <h4>{{post.titulo}}</h4><br>
            <p>{{post.fecha}}</p><br> 
            <p>{{post.resumen}}</p><br>
            <textarea class="materialize-textarea">{{post.contenido}}</textarea><br>       
        </div>
    </div>
</div>
<div class="container" style="text-align:center">
        {% csrf_token %}
        <div class="row">
            <div class="input-field col s6">
                <input placeholder="Nombre" id="nombre" name="nombre" type="text" class="validate">
                <label for="nombre">First Name</label>
            </div>
        </div>
        <div class="row">
            <div class="input-field col s12">
                <input id="mensaje" name="mensaje" type="text" class="validate">
                <label for="mensaje">Comentario</label>
            </div>
        </div>
        <button class="btn waves-effect waves-light" type="submit" name="action">
            <i class="material-icons" id="send">ENVIAR</i>
        </button>
</div>
<div id="mensajes">
    {% include "mensajes.html" %}
</div>
{% endblock %}

{% block scripts %}
<script>
    $("#send").click(function(){        

        var data={
            csrfmiddlewaretoken: '{{ csrf_token }}',
            id:'{{post.id}}',
            nombre:$('#nombre').val(),
            mensaje:$('#mensaje').val(),
        }
        $.ajax({
            type: "POST",
            url: "{% url 'blog:mensaje' %}",
            data: data,
            success: function(result){
                $("#mensajes").html(result);
            },
            error: function(err){
                console.log("ERRRORRRR");
                console.log(err.responseText);
            },
        });
    });
</script>
{% endblock %}